version: "3"
services: 
    mecab:
        build:
            dockerfile: dockerfiles/mecab/Dockerfile
            context: .
        command: echo "テスト" | mecab
    juman:
        build:
            dockerfile: dockerfiles/juman/Dockerfile
            context: .
        command: echo "テスト" | jumanpp
